# Generated by Django 5.1.2 on 2024-10-24 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id_renta', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Identificador de renta')),
                ('fecha_renta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de renta')),
                ('fecha_devolucion_estimada', models.DateTimeField(editable=False, null=True, verbose_name='Fecha de devolución estimada')),
                ('fecha_devolucion', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de devolución')),
                ('estado', models.CharField(choices=[('R', 'Rentado'), ('D', 'Devuelto'), ('T', 'Devuelto tarde'), ('P', 'Sin devolve aun')], default='R', editable=False, max_length=20, verbose_name='Estado de la renta')),
                ('pumapuntos_obtenidos', models.PositiveIntegerField(default=0, editable=False, verbose_name='PumaPuntos obtenidos de esta renta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentas', to='productos.producto', verbose_name='Producto rentado')),
            ],
        ),
    ]
