# Generated by Django 5.1.3 on 2024-11-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta',
            name='estado',
            field=models.CharField(choices=[('R', 'Rentado'), ('D', 'Devuelto'), ('T', 'Devuelto tarde'), ('P', 'Sin devolución aún')], default='R', editable=False, max_length=20, verbose_name='Estado de la renta'),
        ),
    ]
