# Generated by Django 5.1.3 on 2024-11-27 03:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_pumapuntoshistoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_ultimo_reinicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='PumapuntosHistoria',
        ),
    ]
