# Generated by Django 5.1.2 on 2024-10-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Código del producto')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(verbose_name='Descripción del producto')),
                ('existencia', models.PositiveIntegerField(verbose_name='Existencia')),
                ('pumapuntos', models.PositiveIntegerField(verbose_name='PumaPuntos requeridos')),
                ('dias_renta', models.PositiveIntegerField(choices=[(3, '3 días'), (4, '4 días'), (5, '5 días'), (6, '6 días'), (7, '7 días')], verbose_name='Días de renta')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos_imagenes/', verbose_name='Imagen del producto')),
            ],
        ),
    ]
