# Generated by Django 5.1.3 on 2024-11-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
